# version: '3.8'
services:
  erigon:
    build:
      context: .
      dockerfile: Dockerfile.erigon
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8551:8551"
      - "6061:6061"
    networks:
      - eth-net

  beacon:
    build:
      context: .
      dockerfile: Dockerfile.beacon
    volumes:
      - ./config:/config
      - ./network:/network
      - ./secret:/secret
      - ./data:/data
    ports:
      - "13000:13000"
      - "12000:12000/udp"
      - "4000:4000"
      - "3500:3500"
      - "8080:8080"
    depends_on:
      - erigon
    networks:
      - eth-net

  validator:
    build:
      context: .
      dockerfile: Dockerfile.validator
    volumes:
      - ./config:/config
      - ./network:/network
      - ./secret:/secret
      - ./wallets:/wallets
      - ./data:/data
    ports:
      - "8081:8081"
    depends_on:
      - beacon
    networks:
      - eth-net

networks:
  eth-net:
    driver: bridge