name: eva-testnet
version: "3.9"

services:
  erigon:
    image: erigontech/erigon:latest
    container_name: erigon
    user: "root"
    volumes:
      - ./config:/config
      - ./secret:/secret
      - ./data:/data
      - ./logs:/logs
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8551:8551"
      - "6061:6061"
      - "8546:8546"
      - "42069:42069"
    environment:
      - EXTIP=192.168.31.71
      # - EXTIP="$(ip addr show ens5 | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)"
    command:
      - --config=/config/erigon.yaml
      - --nat=extip:192.168.31.71
      - --bootnodes=enode://e3be1105a6d2bd9d087e4e0470167df7d254b935dc51c5786c77a57b876c2edaa47c7a499eac19435ef93ef8c32b5a70f0b6a583d2090a1fea907105f9e46f48@172.31.30.93:30303
    restart: unless-stopped
    networks:
      - eth-net

  beacon:
    image: gcr.io/offchainlabs/prysm/beacon-chain:stable
    container_name: beacon
    volumes:
      - ./config:/config
      - ./network:/network
      - ./secret:/secret
      - ./data:/data
      - ./logs:/logs
    ports:
      - "13000:13000"
      - "12000:12000/udp"
      - "4000:4000"
      - "3500:3500"
      - "8080:8080"
      - "6060:6060"
    command:
      - --config-file=/config/beacon.yaml
      - --checkpoint-sync-url=http://172.31.30.93:3500
      - --p2p-host-ip=192.168.31.71
      - --suggested-fee-recipient=0x6318BC08F350835f8b2e2A542f04e2aB129Ab5C4
      - --peer="/ip4/172.31.30.93/tcp/13000/p2p/16Uiu2HAmLxXjXMpBz77DFGYmSZVZGHkUhDHu1cWrZsaW4DuER9yd"
    restart: unless-stopped
    depends_on:
      - erigon
    networks:
      - eth-net

  validator:
    image: gcr.io/offchainlabs/prysm/validator:stable
    container_name: validator
    volumes:
      - ./config:/config
      - ./network:/network
      - ./secret:/secret
      - ./wallets:/wallets
      - ./data:/data
      - ./logs:/logs
    ports:
      - "8281:8281"
    command:
      - --config-file=/config/validator.yaml
      - --wallet-dir=/wallets/wallet2
      - --suggested-fee-recipient=0x6318BC08F350835f8b2e2A542f04e2aB129Ab5C4
    restart: unless-stopped
    depends_on:
      - beacon
    networks:
      - eth-net

networks:
  eth-net:
    driver: bridge
