networkid: 2248
datadir: /data/erigon
log.dir.path: /data/logs
verbosity: debug
port: 30303
http.api: "eth,erigon,engine,web3,net,debug,trace,txpool,admin"
http.vhosts: "*"
ws: true
ws.port: 8546
allow-insecure-unlock: true
http: true
http.addr: 0.0.0.0
http.corsdomain: "*"
http.port: 8545
p2p.protocol: 68
authrpc.addr: 0.0.0.0
authrpc.port: 8551
authrpc.vhosts: "*"
externalcl: true
metrics: true
metrics.addr: 0.0.0.0
metrics.port: 6061
torrent.port: 42069